# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\x08greet.v1\"\"\n\x0cGreetRequest\x12\x12\n\nfirst_name\x18\x01 \x01(\t\"\x1f\n\rGreetResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\xd9\x02\n\x0cGreetService\x12\x38\n\x05Greet\x12\x16.greet.v1.GreetRequest\x1a\x17.greet.v1.GreetResponse\x12\x43\n\x0eGreetManyTimes\x12\x16.greet.v1.GreetRequest\x1a\x17.greet.v1.GreetResponse0\x01\x12>\n\tLongGreet\x12\x16.greet.v1.GreetRequest\x1a\x17.greet.v1.GreetResponse(\x01\x12\x44\n\rGreetEveryone\x12\x16.greet.v1.GreetRequest\x1a\x17.greet.v1.GreetResponse(\x01\x30\x01\x12\x44\n\x11GreetWithDeadline\x12\x16.greet.v1.GreetRequest\x1a\x17.greet.v1.GreetResponseB Z\x1egithub.com/nirdosh17/protorepob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greet_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\036github.com/nirdosh17/protorepo'
  _globals['_GREETREQUEST']._serialized_start=25
  _globals['_GREETREQUEST']._serialized_end=59
  _globals['_GREETRESPONSE']._serialized_start=61
  _globals['_GREETRESPONSE']._serialized_end=92
  _globals['_GREETSERVICE']._serialized_start=95
  _globals['_GREETSERVICE']._serialized_end=440
# @@protoc_insertion_point(module_scope)
